### ISSUE TITLE
Bracket highlighting in math environnement

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/language-latex2e#11]
It is something we talked about here area/language-latex#128 , do you think it is possible in your package ? It would be really helpful for complex mathematical expressions

**Comment by Aerijo** [comment]
Sure, why not.

Let me know if you get an error, I suspect you will.

**Comment by Aerijo** [comment]
BTW, I still think bracket matching might get somewhat broken if this happens. However, I feel this to be more a problem with `bracket-matcher` itself, rather than the scopes I use. If they offered a way to isolate sets of brackets by scope, that would be nice.

**Comment by PierreMarchand20** [comment]
Well, I can submit an issue in `bracket-matcher` about that if you think it is relevant

**Comment by Aerijo** [comment]
It would be a good feature/enhancement.

**Comment by kylebarron** [comment]
language-latex fixed this by changing the math scope to be not string

**Comment by Aerijo** [comment]
@kylebarron Yeah, it's not string here either. I left the issue open because when you have something like `$[0, 1)$` the bracket matching could be wrong. It only really affects any brackets that contain something like that though.
<img width="165" alt="screen shot 2018-09-05 at 10 26 38 pm" src="https://user-images.githubusercontent.com/22167388/45093118-c9771e00-b15a-11e8-8e70-6e7ec5626837.png">
