### ISSUE TITLE
add support for auto-indent

### ISSUE THREAD

**Issue by caobo** [Aerijo/language-latex2e#3]
I love this package so much more than language-latex.
Could you also add support for auto-indent?
Thank you for your wonderful work.

**Comment by Aerijo** [comment]
Thanks for the compliment, I made this because I was unsatisfied with some of the restrictions of the language-latex package.

A quick fix is to add the following to the settings file in language-latex2e -> settings -> language-latex2e.cson
```
'.text.tex.latex':
  'editor':
    'increaseIndentPattern': '^\\s*(\\\\)begin\\{[^(document)]\\w*\\}'
    'decreaseIndentPattern': '^\\s*(\\\\)end\\{[^(document)]\\w*\\}'
```

This will make the editor indent the cursor after `\begin{env}` and unindent after a `\end{env}`. It does not recognise if the environment is the same in the begin/end, but I don't think overlapping environments are allowed anyway. It also doesn't do this for the document environment, as that's kind of useless.

However, this does not seem to be compatible with the autocomplete packages out there. For this reason, I will not include it as part of a release.

I do intend to add snippets to this package eventually, but can't spend much time doing major work on this package right now (that's also why everything seems half baked; I ran out of time after getting the core stuff like multiline support for optional arguments and such). So for now, you can either include this change on your local version, or use the autocomplete packages like latex-autocomplete or latexer.

Alternatively, you can try out the beautify package. It requires a bit of manual setup, but can be made to work with latex. It will also handle aligning `&` in tables, which is nice. Let me know if you need help with setting it up.

**Comment by Aerijo** [comment]
So I've added snippets to the package now, even though they're limited and only work with some manual changes to other packages (including a core one). I eventually intend to make them a separate package, as snippets are quite distinct from grammar scoping, but I'll keep them for now.

These snippets have indentation built into them. You can change them directly, write your own, use some from a different package, or just stick with the solution I gave before.
